language: d
sudo: false

# Note: DMD v2.078.1-3 has a regression which makes std_data_json
# fails to compile
# This is why LDC v1.8.0 (FE 2.078.3) is not tested.
# Finally, LDC v1.7.0 (FE 2.077.1) is broken with:
# Integer arithmetic operators only work with integral types!
#   %6 = add i8* %4, %5, !dbg !5454
# LLVM ERROR: Broken function found, compilation aborted!

d:
  - dmd-2.082.0
  - dmd-2.081.1
  - dmd-2.080.1
  - dmd-2.079.1
  - dmd-2.078.0
  - dmd-2.077.1
  - ldc-1.11.0
  - ldc-1.10.0
  - ldc-1.9.0
  - dmd-beta

script:
  - dub test --compiler=${DC}
  - dub upgrade && dub test --compiler=${DC}

matrix:
  allow_failures:
    - d: dmd-beta
