name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "[${{ matrix.os }} | ${{ matrix.dc }}]"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc: [dmd-latest, ldc-latest]
        include:
            # No support for Apple Silicon from DMD at this time
            - { os: macOS-latest, dc: ldc-latest }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        env:
          DC: ${{matrix.dc}}
        run: |
          dub test
